==== Query Stream/SuperStream

The `StreamSytem` class expose methods to query a stream or super stream.
The following methods are available:

[%header,cols=3*]
|===

|Method
|Description
|Valid for

|`QuerySequence(string reference, string stream)`
|Retrieves the last publishing id for given a producer Reference and stream. Useful for a producer wants to know the last published id.
| Stream



|`QueryOffset(string reference, string stream)`
|Retrieves retrieves the last consumer offset stored for a given consumer Reference and stream. Useful for as consumer wants to know the last stored offset.
| Stream

|`QueryPartition(string superStream)`
|Returns the list of stream partitions for a given super stream.
| SuperStream

|`StreamStats(string stream)`
|Returns the stream statistics:

- `FirstOffset`: first offset in the stream

- `LastOffset`:  last offset in the stream

- `CommittedChunkId`: the ID (offset) of the committed chunk (block of messages) in the stream.

It is the offset of the first message in the last chunk confirmed by a quorum of the stream cluster members (leader and replicas).
    
The committed chunk ID is a good indication of what the last offset of a stream can be at a
given time. The value can be stale as soon as the application reads it though, as the committed
chunk ID for a stream that is published to changes all the time.
    
return committed offset in this stream
| Stream

|=== 
