name: publish-nuget

on:
  workflow_call:
    secrets:
      NUGET_API_KEY:
        required: true

jobs:
  publish-nuget:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.x
            7.x
            8.x
            9.x
      - uses: actions/cache@v4
        with:
          path: |
            ~/.nuget/packages
            ~/.local/share/NuGet/v4-cache
          key: ${{ runner.os }}-v2-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-v2-nuget-
      - name: Build (Release)
        run: dotnet build ./Build.csproj --verbosity=normal --configuration=Release /p:CI=true
      - name: Publish to NuGet
        run: dotnet nuget push --skip-duplicate --api-key ${{secrets.NUGET_API_KEY}} --source 'https://api.nuget.org/v3/index.json' ${{github.workspace}}/packages/RabbitMQ.Stream.Client.*.nupkg
