name: publish rabbitmq-stream-dotnet-client

on:
  create:
    tags:
      - '*'
  push:
    tags:
      - '*'

jobs:
  call-build-test:
    uses: ./.github/workflows/build-test.yaml
  call-publish-nuget:
    uses: ./.github/workflows/publish-nuget.yaml
    needs: call-build-test
    secrets: inherit
